#!/bin/bash

(return 0 2>/dev/null) && sourced=1 || sourced=0
test $sourced -eq 0 && echo $(basename "$0") "must be sourced" && exit 2

if [[ -z "$LANG" ]]; then
  export LANG=en_US.UTF-8
fi

# set the time zone and format so prompts and logs are consistent
export TZ=UTC
export TIME_STYLE=long-iso
export LC_ALL=en_DK.UTF-8

export REPO_USER_DIR="$REPO_DIR/user"
export PATH="$REPO_USER_DIR/bin:/user/local/bin:$PATH"

cd "$REPO_USER_DIR/build"


