#!/bin/bash
# this is sourced into the environment with the repo_env command

# set the time zone and format so prompts and logs are consistent
export TZ=UTC
export TIME_STYLE=long-iso

export REPO_USER_DIR="$REPO_DIR/user"
export PATH="$REPO_USER_DIR/executable:$PATH"

# protect the system files
cd "$REPO_USER_DIR"
