#!/bin/bash

if [[ "$LFS_ENV" != "m1_root" ]];then
  echo $(basename "$0") "must be run in env_m1_root"
  exit 1
fi

frame s7.02_m2_chown_root
frame s7.03_devices

mkdir -p "$LFS_M2_FILESYSTEM"/usr/local/bin

# not from the book, but we need the time stamp
cp "$REPO_USER_DIR"/cantari/Z  "$LFS_M2_FILESYSTEM"/usr/local/bin


