#!/bin/bash

if [[ "$LFS_ENV" != "m1" ]];then
  echo $(basename "$0") "only intended to be run when \$LFS_ENV == 'm1'"
  exit 1
fi

frame book_m1

# this is unnecessary on this system, as it is about the same speed to rebuild up to this point
# checkpointing also takes a lot of disk space which might become an issue
# frame checkpoint m2_filesystem_after_book_m1

# exports a copy of the scripts to m2_filesystem and runs the pre-chroot portion of chapter 7
frame env_m1_root book_m1_to_m2

# This will be the last command that shows in the logs of the m1 build directory. After this the scripts start
# writing the logs in the m2_filesystem/sbin/LFS directory.
frame env_m1_root env_m2 book_m2

# this doesn't work, at this point there are things on the disk that tar does not like
# checkpointing also takes a lot of disk space which might become an issue
# frame environment_root checkpoint m2_filesystem_after_book_m2

