#!/bin/bash

# check book_m1 to see if it downloads the upstream or not depending on your needs

# we want to move a system where the configuration is built up front, then everything runs
# currently the admin must mount the target device at /mnt/m2_filesyste before starting
# replace /dev/xxxx with the device name, probably something like /dev/sdb1
#
# use your actual target device, /dev/sdb1 might be something different on your system
# mkfs.ext4 /dev/sdb1
# sudo mkdir /mnt/m2_filesystem
# sudo mount /dev/sdb1 /mnt/m2_filesystem
# chown lfs:lfs /mnt/m2_filesystem
export LFS_M2_FS="/mnt/m2_filesystem"

# can't frame this or the 'really?' prompt goes into the logs ...
# env_m1 env_m1_root m2_filesystem_wipe

env_m1 frame book

