#!/bin/bash

if [[ "$LFS_ENV" != "m2" ]];then
  echo $(basename "$0") "only intended to be run in env_m2"
  exit 1
fi

s10.2_fstab

section="
linux
"

IFS=$'\n'; for s in $section;do
  frame env_incantatio $s s10_$s
done

# 
s10.3.2_module_load_order

# s10.4 book proposes to make a rescue copy of the boot record, but where to put it?

