#!/bin/bash

if [[ "$LFS_ENV" != "m2" ]];then
  echo $(basename "$0") "only intended to be run in env_m2"
  exit 1
fi

...


section="
lfs-bootscripts
"

IFS=$'\n'; for s in $section;do
  frame env_incantatio $s s9_$s
done

