#!/bin/bash

if [[ "$LFS_ENV" != "m1" ]];then
  echo $(basename "$0") "only intended to be run in env_m1"
  exit 1
fi

frame s3.2_wget_all_document
frame s3.2_wget_all_incantatio
frame s3.2_wget_all_patch

