#!/bin/bash
set -e

if [[ "$LFS_ENV" != "m1" ]];then
  echo $(basename "$0") "must be run in env_m1"
  exit 1
fi

section="
m4
ncurses
bash
coreutils
diffutils
file
findutils
gawk
grep
gzip
make
patch
sed
tar
xz
binutils
gcc          
"

IFS=$'\n'; for s in $section;do
  # echo s6_$s
  eval frame env_incantatio $s s6_$s
done
