#!/bin/bash

# s7.02 or s7.03 are part of book_m1_to_m2

if [[ "$LFS_ENV" != "m2" ]];then
  echo $(basename "$0") "only intended to be run in env_m2"
  exit 1
fi

# contain further builds to the m2 directory tree
frame s7.05_mkdirs
frame s7.06_essential

frame env_incantatio "gcc" s7.07_libstdc++

section="
gettext
bison
perl
Python
texinfo
util-linux
"

IFS=$'\n'; for s in $section;do
  # echo s7_$s
  frame env_incantatio $s s7_$s
done

#s7.14_checkpoint
s7.14_cleanup


