#!/bin/bash

if [[ "$LFS_ENV" != "m2" ]];then
  echo $(basename "$0") "only intended to be run in env_m2"
  exit 1
fi

section="
lfs-bootscripts
"

IFS=$'\n'; for s in $section;do
  frame env_incantatio $s s9_$s
done

s9.5.1_eth0_exmaple
s9.5.2_resolv.conf
s9.5.3_hostname
s9.5.4_etc_hosts
s9.6.2_sysvinit
s9.6.4_clock
s9.8_inputrc
s9.9_shells
