#!/bin/bash

# https://www.linuxfromscratch.org/blfs/view/systemd/postlfs/grub-efi.html
# grub2
#   efibootmgr
#
#     efivar
#       mandoc - funny this is said to be required
#
#     popt
#       optional - Doxygen
#
#     recommended: freetype
#       recommended: HarfBuzz
#       optional: Brotli
#       otpional for docs: docwriter
#
#     optional: lvm2
#       libaio
#       optional: many
#
# note that popt is an insecure download

#--------------------------------------------------------------------------------
# packages to be bult

if [[ "$LFS_ENV" != "m1" ]];then
  echo $(basename "$0") "must be run in env_m1"
  exit 1
fi

incantatio_dir="$REPO_USER_DIR/build/upstream/incantatio"
mkdir -p "$incantatio_dir"
pushd "$incantatio_dir"

link="
https://ftp.gnu.org/gnu/grub/grub-2.06.tar.xz
https://unifoundry.com/pub/unifont/unifont-14.0.04/font-builds/unifont-14.0.04.pcf.gz
https://github.com/rhboot/efibootmgr/archive/18/efibootmgr-18.tar.gz
https://github.com/rhboot/efivar/releases/download/38/efivar-38.tar.bz2
https://mandoc.bsd.lv/snapshots/mandoc-1.14.6.tar.gz
http://ftp.rpm.org/popt/releases/popt-1.x/popt-1.18.tar.gz
https://downloads.sourceforge.net/freetype/freetype-2.12.1.tar.xz
"

IFS=$'\n'; for l in $link;do
  # wget -nv $l
  curl -LOfsS $l
done

popd

#--------------------------------------------------------------------------------
# documentation

document_dir="$REPO_USER_DIR/build/upstream/document"
mkdir -p "$document_dir"
pushd "$document_dir"

link="
https://downloads.sourceforge.net/freetype/freetype-doc-2.12.1.tar.xz
"

IFS=$'\n'; for l in $link;do
  #   wget -nv $l
  curl -LOfsS $l
done

popd
  



