#!/bin/bash
# source this because it exports the LFS_LOG_DIR
# careful, $REPO_USER_DIR may be different in m1fs and m2fs

if [[ -z "REPO_USER_DIR" ]];then
  echo "$(basename "$0") no \$REPO_USER_DIR" > /dev/stderr
  exit 1
fi

#https://stackoverflow.com/questions/2683279/how-to-detect-if-a-script-is-being-sourced
(return 0 2>/dev/null) && sourced=1 || sourced=0
test $sourced -eq 0 && echo $(basename "$0") "must be sourced" && exit 2

# crates a time stamped directory for this build's logs, this is collision free due to using mktemp, and race free
log_dir="$REPO_USER_DIR/build/log"
if [[ ! -d "$log_dir" ]];then
  mkdir -p "$log_dir" || { echo $(basename "$0") "can't make log dir" > /dev/stderr ; exit 2 ; }
fi
stamp="$(Z)"
export LFS_LOG=$(basename $(mktemp -d --tmpdir="$log_dir" -t "$stamp"'-XXXXXXXXXX' ))


frame="$log_dir/$LFS_LOG/frame"
build="$log_dir/$LFS_LOG/build"
telltale="$log_dir/$LFS_LOG/telltale"

cat <<EOF | tee "$frame" | tee "$build" | tee "$telltale"
#--------------------------------------------------------------------------------
# $stamp
#    frame-initialize sourced from: $0  
#--------------------------------------------------------------------------------
EOF
