#!/bin/bash
# This might require sudo_LFS depending on the stage in the build that it is run at.
# This is dangerous. This is the kind of thing that causes a person to use an emulated m1 machine.
# set -x

if [[ "$LFS_ENV" != "m1_root" ]];then
  echo $(basename "$0") "must be run in env_m1_root"
  exit 1
fi

m2_unbind

# skip /mnt just in case it did not unmount (has happened ...)
echo "rm -rf the following:"
find "$LFS_M2_FILESYSTEM" \
  -maxdepth 1 -mindepth 1 \
  ! -name "mnt" \
  -print \
  \( -exec rm -rf {} \; -o -quit \)

rmdir -v "$LFS_M2_FILESYSTEM"/mnt

# set +x
