#!/bin/bash

if [[ "$LFS_ENV" != "m1_root" ]];then
 echo $(basename "$0") "must be run from env_m1_root"
 exit 1
fi

# found that the absolute pathname is necessary, independent of the current pwd
umount /mnt/m2_filesystem/mnt/Lustucru || true
rmdir -v /mnt/m2_filesystem/mnt/Lustucru || true

umount -v $LFS_M2_FILESYSTEM/dev/pts || true
umount -v $LFS_M2_FILESYSTEM/{sys,proc,run,dev} || true


