#!/bin/bash
set -x

if [[ "$LFS_ENV" != "m1_root" ]];then
 echo $(basename "$0") "must be run from env_m1_root"
 exit 1
fi

# found that the absolute pathname is necessary, independent of the current pwd
umount -v "$LFS_M2_FS$LFSM2_REPO_DIR"
rmdir -v "$LFS_M2_FS$LFSM2_REPO_DIR"

umount -v "$LFS_M2_FS"/dev/pts
umount -v "$LFS_M2_FS"/{sys,proc,run,dev}



