#!/bin/bash

if [[ "$LFS_ENV" != "m2" ]];then
  echo $(basename "$0") "must be run in env_m2"
  exit 1
fi

make mrproper

#see LFS book for LANG variable

# make menuconfig
make defconfig
# it printed:
# *** Default configuration is based on 'x86_64_defconfig'
# # configuration written to .config
# according to book, explained at https://www.linuxfromscratch.org/hints/downloads/files/kernel-configuration.txt

# need to set .config file values if not defaults, make menuconfig will do this.  Can we just
# put the values directly into .config?

make
make modules_install

# if there is a separate /boot directory
mount --bind /boot /mnt/lfs/boot

cp -iv arch/x86/boot/bzImage /boot/vmlinuz-5.16.9-lfs-11.1
cp -iv System.map /boot/System.map-5.16.9
install -d /usr/share/doc/linux-5.16.9
cp -r Documentation/* /usr/share/doc/linux-5.16.9
