#!/bin/bash

if [[ "$LFS_ENV" != "m1" ]];then
  echo $(basename "$0") "must be run in env_m1"
  exit 1
fi

./configure --prefix=/usr                     \
            --host=$LFS_TGT                   \
            --build=$(build-aux/config.guess) \
            --enable-install-program=hostname \
            --enable-no-install-program=kill,uptime

make
make DESTDIR=$LFS_M2_FILESYSTEM install
mv -v $LFS_M2_FILESYSTEM/usr/bin/chroot              $LFS_M2_FILESYSTEM/usr/sbin
mkdir -pv $LFS_M2_FILESYSTEM/usr/share/man/man8
mv -v $LFS_M2_FILESYSTEM/usr/share/man/man1/chroot.1 $LFS_M2_FILESYSTEM/usr/share/man/man8/chroot.8
sed -i 's/"1"/"8"/'                    $LFS_M2_FILESYSTEM/usr/share/man/man8/chroot.8

