#!/bin/bash

if [[ "$LFS_ENV" != "m1" ]];then
  echo $(basename "$0") "must be run in env_m1"
  exit 1
fi

./configure --prefix=/usr                   \
            --localstatedir=/var/lib/locate \
            --host=$LFS_TGT                 \
            --build=$(build-aux/config.guess)
make
make DESTDIR=$LFS_M2_FS install

