#!/bin/bash

if [[ "$LFS_ENV" != "m1" ]];then
  echo $(basename "$0") "only intended to be run in env_m1"
  exit 1
fi

./configure --prefix=/usr   \
            --without-guile \
            --host=$LFS_TGT \
            --build=$(build-aux/config.guess)
make
make DESTDIR=$LFS_M2_FILESYSTEM install

