#!/bin/bash

if [[ "$LFS_ENV" != "m2" ]];then
  echo $(basename "$0") "must be run in env_m2"
  exit 1
fi


cd /source/$SOURCE_DIR
echo "In directory: " $(pwd)



./configure --prefix=/usr   \
            --enable-shared \
            --without-ensurepip

# to get Python to make had to build libffi way up in 8.49 hmmmm
# still give error that it can not find TCL header, but still seems to build
make

make install
