#!/bin/bash

if [[ "$LFS_ENV" != "m2" ]];then
  echo $(basename "$0") "only intended to be run in env_m2"
  exit 1
fi

./configure --prefix=/usr                      \
            --docdir=/usr/share/doc/bash-5.1.16 \
            --without-bash-malloc              \
            --with-installed-readline

make
chown -Rv tester .

su -s /usr/bin/expect tester << -EOF
	set timeout -1
	spawn make tests
	expect eof
	lassign [wait] _ _ _ value
	exit $value
EOF

make install

# this would not do the same for our scripts as it does when running this manually
# exec /usr/bin/bash --login
