#!/bin/bash
# set -x

if [[ "$LFS_ENV" != "m2" ]];then
  echo $(basename "$0") "must be run in env_m2"
  exit 1
fi

echo 'This should output "span ls" '
expect -c "spawn ls"

patch -Np1 -i "$REPO_USER_DIR/build/upstream/patch/binutils-2.38-lto_fix-1.patch"

sed -e '/R_386_TLS_LE /i \   || (TYPE) == R_386_TLS_IE \\' \
    -i ./bfd/elfxx-x86.h

mkdir -v build
cd       build

../configure --prefix=/usr       \
             --enable-gold       \
             --enable-ld=default \
             --enable-plugins    \
             --enable-shared     \
             --disable-werror    \
             --enable-64-bit-bfd \
             --with-system-zlib

make tooldir=/usr
make -k check
make tooldir=/usr install
rm -fv /usr/lib/lib{bfd,ctf,ctf-nobfd,opcodes}.a
