#!/bin/bash

if [[ "$LFS_ENV" != "m2" ]];then
  echo $(basename "$0") "must be run in env_m2"
  exit 1
fi

./configure --prefix=/usr    \
            --disable-static \
            --enable-libgdbm-compat

make
make check
make install
