#!/bin/bash

if [[ "$LFS_ENV" != "m2" ]];then
  echo $(basename "$0") "must be run in env_m2"
  exit 1
fi

./configure --prefix=/usr        \
            --disable-static     \
            --enable-thread-safe \
            --docdir=/usr/share/doc/mpfr-4.1.0

make
make html

make check

make install
make install-html
