#!/bin/bash

if [[ "$LFS_ENV" != "m2" ]];then
  echo $(basename "$0") "only intended to be run in env_m2"
  exit 1
fi

patch -Np1 -i "$LFS_BUILD_DIR/patch/sysvinit-3.01-consolidated-1.patch"
make
make install
