#!/bin/bash

# book used /mnt/lfs
export LFS=/mnt/lfs

# I moved the source directory /mnt/sources so that I could manipulate the directory structure separately
# otherwise this would have been $LFS/sources
#
export SOURCES=/mnt/sources

