#!/bin/bash

script="$1"
if [[ -z "$script" ]];then
  echo $0 requires a first argument as a script name
  exit
fi

sudo chroot "$LFS" /usr/bin/env -i   \
    HOME=/root                  \
    TERM="$TERM"                \
    PS1='(lfs chroot) \u:\w\$ ' \
    PATH=/usr/bin:/usr/sbin     \
    SOURCE_DIR="$SOURCE_DIR"    \
    "$script"

