#!/bin/bash


# https://www.linux-kvm.org/page/Main_Page
# https://en.wikipedia.org/wiki/Kernel-based_Virtual_Machine
# https://libvirt.org/
# https://en.wikipedia.org/wiki/Libvirt

#--------------------------------------------------------------------------------
# debian 11
# hopefully someone will make this right
# apt-get install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils


method=0

#--------------------------------------------------------------------------------
# fedora 35
#
    # https://docs.fedoraproject.org/en-US/quick-docs/getting-started-with-virtualization/
    # the libvirtd creates the ip bridge virbr0, do not need to create it manually

if [[ "$method" == 0 ]]; then
    echo "dnf installing @virtutalization - using libvert"
    dnf install @virtualization
    systemctl start libvirtd
    systemctl enable libvirtd
    exit
fi

# if [[ "$method" == 1 ]]; then



