#!/bin/bash

# F35 did a libvert install
# for the libvert install just do this:
#    > virt-manager
#        then run the machine, open the machine if you want a console
#
#  for Debian 11 it went something like this:

set -x

mathod=0
if [ "$method" == 0 ]; then
    echo "using virtual manager"
    virt-manager
    exit
fi

if [ "$method" == 1 ]; then
    echo "using virt-install command line "

    mem="$1" 
    disk="$2" 
    cores="$3" 
    isntall_image="$4"
    eth0="$5"

    lib="$PROJECT_HOME"/lib

    if [ -z "$1" ]; then
        mem=4G
    fi
    if [ -z "$2" ]; then
        disk=qemu-disk-0
    fi
    if [ -z "$3" ]; then
        cores=11
    fi
    if [ -z "$4" ]; then
        isntall_image=debian-11.2.0-amd64-netinst.iso
    fi
    if [ -z "$5" ]; then
        eth0=enp1s0
    fi



    # Roberts fast launch command
    # qemu-system-x86 -cpu max -smp $cores -enable-kvm -hda "$LIB"/"$disk" -cdrom "$LIB"/"$isntall_image" -device e1000.netdev="$eth0" -netdev user.id=net0.hostfwd=tcp::5555-:22 -m "$mem" -boot d

    # command having just installed qemu-kvm
    # debian, Robert
    # qemu-kvm -cpu max -smp $cores -enable-kvm -hda "$lib"/"$disk" -cdrom "$lib"/"$isntall_image" -device e1000.netdev="$eth0" -netdev user.id=net0.hostfwd=tcp::5555-:22 -m "$mem" -boot d 

    # this might work on debian, uses the virt tools, note the bridge virbr0 and does not have the cool ssh port .. or does it?  graphics is set to vnc ... hmmm
    # https://docs.fedoraproject.org/en-US/quick-docs/getting-started-with-virtualization/
    # This private network will use a 192.168.x.x

    virt-install --name virtual_debian \
    --description 'Debian 11' \
    --ram 4096 \
    --vcpus "$cores" \
    --disk path="$lib"/"$disk",size=20 \
    --os-type linux \
    --os-variant debian11 \
    --network bridge=virbr0 \
    --graphics vnc,listen=127.0.0.1,port=5901 \
    --noautoconsole
    #--cdrom "$lib"/"$isntall_image" \


    # gives this mesage
        # Domain installation still in progress. You can reconnect to
        # the console to complete the installation process.
    # run this to continue:

    virt-viewer
fi

set +x
