#!/bin/bash
set -x

script="$@"
if [[ -z "$script" ]]; then
  script=/bin/bash\ --init-file\ "$REPO_USER_DIR"/library/bashrc_lfs
fi

if [[ -z "$LFS_M2_FILESYSTEM" ]];then
  echo $0 "requires variable LFS_M2_FILESYSTEM to be set"
  exit 1
fi

if [[ -z "$TERM" ]];then
  echo $0 "requires variable TERM to be set"
  exit 2
fi

# this is what the repo variables will look like after the chroot, i.e. within the m2 filesystem
m2fs_repo_home="/mnt"
m2fs_repo_dir="$m2fs_repo_home"/"$REPO"
m2fs_repo_user_dir="$m2fs_repo_dir"/user

repo_dir_target="$LFS_M2_FILESYSTEM"/"$m2fs_repo_dir"
mkdir -p "$repo_dir_target"
mount --bind "$REPO_DIR" "$repo_dir_target"

chroot "$LFS_M2_FILESYSTEM" /usr/bin/env --ignore-environment \
  HOSTNAME="$HOSTNAME"\
  USERNAME="$USERNAME"\
  TMP="/tmp"\
  TZ="$TZ"\
  TIME_STYLE="$TIME_STYLE"\
  LANG="$LANG"\
  TERM="$TERM" \
  TERMCAP="$TERMCAP" \
  EDITOR="$EDITOR" \
  PPS1="$PPS1"\
  PPS2="$PPS2"\
  REPO_HOME="$m2fs_repo_home"\
  REPO="$REPO"\
  REPO_DIR="$m2fs_repo_dir"\
  PROJECT="$PROJECT:book_after_chroot"\
  LFS_M2_FILESYSTEM="/"\
  "$m2fs_repo_user_dir"/executable/environment_book_m2-1  $script

set +x
