#!/bin/bash
# set -x

script="$@"

if [[ -z "$script" ]]; then
  script=/bin/bash\ --init-file\ "$M2FS_REPO_USER_DIR"/library/bashrc_lfs
fi

if [[ -z "$LFS_M2_FILESYSTEM" ]];then
  echo $(basename "$0") "requires variable LFS_M2_FILESYSTEM to be set" > /dev/stderr
  exit 1
fi

if [[ -z "$TERM" ]];then
  echo $(basename "$0") "requires variable TERM to be set"  > /dev/stderr
  exit 2
fi

if [[ !  -x "$LFS_M2_FILESYSTEM"/usr/local/bin/Z ]]; then
  echo $(basename "$0") "no \$LFS_M2_FILESYSTEM/usr/loca/bin/Z, did you run 'book_m1_to_m2' ?"  > /dev/stderr
  exit 1
fi

chroot "$LFS_M2_FILESYSTEM" /usr/bin/env --ignore-environment \
  HOSTNAME="$HOSTNAME"\
  USERNAME="$USERNAME"\
  TMP="/tmp"\
  TZ="$TZ"\
  TIME_STYLE="$TIME_STYLE"\
  LANG="$LANG"\
  TERM="$TERM" \
  TERMCAP="$TERMCAP" \
  EDITOR="$EDITOR" \
  PPS1="$PPS1"\
  PPS2="$PPS2"\
  REPO_HOME="$M2FS_REPO_HOME"\
  REPO="$REPO"\
  REPO_DIR="$M2FS_REPO_DIR"\
  PROJECT="$PROJECT:book_after_chroot"\
  LFS_M2_FILESYSTEM="/"\
  "$M2FS_REPO_USER_DIR"/executable/environment_book_m2-1  $script

#set +x
