#!/bin/bash
# adds timing information and logging
#
script=$@

if [[ -z "$LFS_BUILD_DIR" ]];then
  echo "$(basename "$0") no \$LFS_BILD_DIR"
  exit 1
fi
if [[ ! -d "$LFS_BUILD_DIR/log" ]];then
  mkdir -p "$LFS_BUILD_DIR/log" || { echo $(basename $(basename "$0")) "can't make log dir" && exit 2 ; }
fi
if [[ -z "$LFS_FRAME_LOG" ]];then
  echo "$(basename "$0") no \$LFS_FRAME_LOG"
  exit 3
fi
if [[ -z "$LFS_BUILD_LOG" ]];then
  echo "$(basename "$0") no \$LFS_BUILD_LOG"
  exit 4
fi

frame_log_path="$LFS_BUILD_DIR/log/$LFS_FRAME_LOG"
build_log_path="$LFS_BUILD_DIR/log/$LFS_BUILD_LOG"
stamp=$(Z)
cat <<EOF | tee -a "$frame_log_path" >> "$build_log_path"

#--------------------------------------------------------------------------------
# $stamp
# start of: $script
#
#
EOF

{ { time $script ; } 2>&1 1>&3 | tee -a "$frame_log_path" ; } 1>> "$build_log_path" 3>&1

stamp=$(Z)
cat <<EOF | tee -a "$frame_log_path" >> "$build_log_path"

#
#
# end of: $script
# $stamp
#--------------------------------------------------------------------------------

EOF

