#!/bin/bash

# for F35
# virt-manager has a create machine options that runs through menus to do this

name="$1" 
size="$2"

if [ -z "$1" ]; then
    name=qemu-disk-0
fi
if [ -z "$2" ]; then
    size=30G
fi

# qemu-img create -f raw "$LIB"/"$name" "$size"

# in case we want to archive this disk, it is better that it is smaller
qemu-img create -f qcow2 "$LIB"/"$name" "$size"


