#!/bin/bash
# set -x

# kind of interesting, making the build directory inside the source directory
mkdir -v build
cd       build

# gosh wonder where this was set, perhaps in the environment ... yes
# > echo $LFS_TGT
# x86_64-lfs-linux-gnu

# configure exits with 1, which bash interprets as an error, then set -e stops the script
../configure --prefix=$LFS_M2_FILESYSTEM/tools \
             --with-sysroot=$LFS_M2_FILESYSTEM \
             --target=$LFS_TGT   \
             --disable-nls       \
             --disable-werror  

make
# Robert has 
# make install -j1
# wonder if there is a reason for that
make install

# set +x
