#!/bin/bash

./configure --prefix=/usr                   \
            --build=$(support/config.guess) \
            --host=$LFS_TGT                 \
            --without-bash-malloc
make
make DESTDIR=$LFS_M2_FILESYSTEM install
ln -sv bash $LFS_M2_FILESYSTEM/bin/sh


