#!/bin/bash

# kind of interesting, making the build directory inside the source directory
mkdir -v build
cd       build

# gosh wonder where this was set, perhaps in the environment ... yes
# > echo $LFS_TGT
# x86_64-lfs-linux-gnu

# configure exits with 1, which bash interprets as an error, then set -e stops the script
../configure --prefix=$M2_ROOT/tools \
             --with-sysroot=$M2_ROOT \
             --target=$LFS_TGT   \
             --disable-nls       \
             --disable-werror  

make
make install



