#!/bin/bash
# build configuration
# this is sourced into the environment
# perhpas add a flag for installing documenation or not

export MAKEFLAGS="-j12" 

# where the target device is mounted on m1.
# put the wrong device here and your m1 build system might be destroyed
export LFS_M2_DEVICE=/dev/sda

# these partitions are relative to where the target device is mounted on m1.
export LFS_M2_DEVICE_EFI="$LFS_M2_DEVICE"1
export LFS_M2_DEVICE_SWAP="$LFS_M2_DEVICE"2
export LFS_M2_DEVICE_FS="$LFS_M2_DEVICE"3

# where to mount the m2 target device
export LFS_M2_EFI="/mnt/m2_efi"
export LFS_M2_FS="/mnt/m2_fs"

# These values to be used in the m2 environment for REPO_HOME etc.
export LFSM2_LFS_M2_FS="/"
export LFSM2_REPO_HOME="/mnt"
export LFSM2_REPO_DIR="$LFSM2_REPO_HOME/$REPO"
export LFSM2_REPO_USER_DIR="$LFSM2_REPO_DIR/user"




