#!/bin/bash
#
set -x

script_name=$(basename $(mktemp -p $LFS/tmp -t))
script_path_0="$LFS/tmp/$script_name"
script_path_1="/tmp/$script_name"

cat > "$script_path_0" <<-EOF
  set -x

  ls /

  set +x
EOF
chmod ug+x "$script_path_0"

cat "$script_path_0"

sudo chroot "$LFS" "$script_path_1"

set +x
