#!/bin/bash
#

archive_directory="~/user/archive/"
if [[ -z "$archive_directory" ]]; then
  echo '$0 could not find the archive directory "$archive_directory"'
  exit 1
fi

archive_file=$(mktemp --tmpdir="$archive_directory" book_m1_build.XXXXX.tgz)
echo "archiving $M2_ROOT before the chroot"

tar -tzf book_m1_checkpoint.tgz $M2_ROOT
