#!/bin/bash
# Make the top of the m2 tree the root of the file system, then run the script

script="$1"
if [[ -z "$script" ]];then
  echo $0 " requires a first argument as a script name"
  exit
fi

echo "setting root of file system to:" "$M2_ROOT"
sudo chroot "$M2_ROOT" /usr/bin/env -i\
     HOME=/root                  \
     M2_ROOT=/                   \
     TERM="$TERM"                \
     PS1='(lfs chroot) \u:\w\$ ' \
     PATH=/usr/bin:/usr/sbin:/usr/sbin/LFS\
     "$script"


