#!/bin/bash
# this must be sourced into the build
# except for the log file variables this comes from section 4.4

script="$@"
# if [[ -z "$script" ]]; then
#   echo "$0 requires a script to call"
#   exit 1
# fi

# wrapped script into a string, then 
# env -i <(echo "$wrapped_script")
# ah heck, this does not work

wrapped=$(mktemp)
if [ $? -ne 0 ]; then
    echo "$0: couldn't create temp"
    exit 2
fi
chmod u+x "$wrapped"

# Variables with the $ expand now.  Those with \$ remain as part of the document.
cat >"$wrapped" <<-EOF

	# according to the book	   
	umask 022
	M2_ROOT="/mnt/m2_root"
	LC_ALL=POSIX
	LFS_TGT=$(uname -m)-lfs-linux-gnu
	PATH=/usr/bin
	if [ ! -L /bin ]; then 
	  export PATH=/bin:"\$PATH"
	 fi
	PATH="\$M2_ROOT"/tools/bin:"\$PATH"  # local build tools capable of targetting the m2 directory tree
	CONFIG_SITE="\$M2_ROOT"/usr/share/config.site
	MAKEFLAGS='-j12'  # this might cause problems for some builds
	export M2_ROOT LC_ALL LFS_TGT PATH CONFIG_SITE MAKEFLAGS 

	# our local systems programs, eg. Z
	PATH=/usr/local/bin:"\$PATH"

	# repo environment
	REPO_HOME=$REPO_HOME
	PROJECT_HOME=$PROJECT_HOME
	PROJECT=$PROJECT
	PATH="\$REPO_HOME"/executable/LFS/:"\$PATH" # chroot has a different path for finding the build scripts
	export REPO_HOME PROJECT_HOME PROJECT PATH

	# for our build scripts
	BUILD_LOG="build.log"
	FRAME_LOG="frame.log"
	export BUILD_LOG FRAME_LOG	  

	# prompt so that dirtrack works in emacs, timezone
	PS1="$PPS1"
	PS2="$PPS2"
	TZ=UTC
	TIME_STYLE=long-iso
	export PS1 PS2 TZ TIME_STYLE

	$script
EOF

env -i "$wrapped"
