#!/bin/bash
#
# About sudo
#   This script uses sudo -E to prevent the environment from being erased. Sudo only appears here
#   at the top level.
#
#   Be sure to modify the /etc/suders file so sudo does not ask for a password, otherwise a person will have to
#   be present to type the sudo password before it times out. Emacs tramp also gets messed up by the
#   sudo password prompts.
#
# Control-C does not work to stop this script.  Not sure why.  Suggest running it in the background then kill the job,
# or using pstree -p, and then to be careful to kill the parent.  Good to check pstree -p so as to see if other builds
# are running, particularly if ther ehave been problems.

frame-0
frame book_m1_environment sudo -E m2_wipe
frame book_m1_environment book_m1

# s7_14_checkpoint is suggested after chapter 7, but I prefer to do the archive here after the m1 phase is finished
frame book_m1_environment archive_m1

# Find the scripts export and first couple of sections of chapter 7 in book_transition.
#
frame book_m1_environment sudo -E book_transition

# In a prior version I ran book_m2_environment on each inner build call. Here it is called only once on the outer
# book_m2 call instead.  This inner call approach has the advantage that it makes only one local build.log and
# frame.log; however it has the disadvantage that the sudo timer can run out between builds.  I believe that sudo also
# times out when no password is provided for a long time, so it can make quite a mess. With this outer call approach the
# sudo password is asked for only once.

# In m1, the frame log will show this call, but once in the book_m2_environment, the frames called in the book_m2
# script will be on m2.
frame book_m1_evironment sudo -E book_m2_environment book_m2
