#!/bin/bash
#

# emacs tramp confused by the shell ops for the sudo password, so lets get this out of the way.
sudo ls

# this is the top level call to build LFS
#
set -x
set -e
export SHELLOPTS

# start by cleaning the target media
wipe_m2

# I don't know how this script would act with the set -e, if it would exit with a correct code, ir
# if it would exit without a message.  It is a good idea to run it first, but it is not necessary
# for the build.
#
# s2.2_check_script

# We already have the packages and patches, so don't need to run this
#
# s3.2_wget_all_packages
# s3.2_wget_all_patches

# give some structure to the m2 directory tree
s4.2_target_dir_tree

# user space package installs on the m2 directory tree
#
s5.2_binutils
