#!/bin/bash

section="
m4
ncurses
bash
coreutils
diffutils
file
findutils
gawk
grep
gzip
make
patch
sed
tar
xz
binutils
gcc          
"

IFS=$'\n'; for s in $section;do
  # echo s6_$s
  eval frame package_scope $s s6_$s
done
