#!/bin/bash

# give ownership of the m2 directoy tree to root
s7.02_m2_directory_tree_chown_root

# build device file in the m2 directory tree
s7.03_devices

# contain further builds to the m2 directory tree
chroot_m2 s7.05_mkdirs
chroot_m2 s7.06_essential
chroot_m2 package_scope "gcc" s7.07_libstdc++
chroot_m2 s7.08_gettext
chroot_m2 s7.09_Bison
chroot_m2 s7.10_Perl
chroot_m2 s7.11_Python
chroot_m2 s7.12_Texinfo
chroot_m2 s7.13_Util-linux
chroot_m2 s7.14_cleanup_m2
s7.14_cleanup_m1

