#!/bin/bash

# s7.02 or s7.03 are part of book_transition

# contain further builds to the m2 directory tree
frame s7.05_mkdirs
frame s7.06_essential

frame package_scope "gcc" s7.07_libstdc++

section="
gettext
bison
perl
Python
texinfo
util-linux
"

IFS=$'\n'; for s in $section;do
  # echo s7_$s
  frame package_scope $s s7_$s
done

s7.14_cleanup


