#!/bin/bash

built="
man-pages
iana-etc
glibc
zlib
bzip2
"

section="
xz
zstd
file
readline
m4
bc
flex
tcl
expect
dejagnu
binutils
"

prevenir="
gmp
mpfr
mpc
attr
acl
libcap
shadow
gcc
pkg-config
ncurses
sed
psmisc
gettext
bison
grep
bash
libtool
gdbm
gperf
expat
inetutils
less
perl
xml
intltool
autoconf
automake
openssl
kmod
libelf
libffi
Python
ninja
meson
coreutils
check
diffutils
gawk
findutils
groff
grub
gzip
iproute2
kbd
libpipeline
make
patch
tar
texinfo
vim
eudev
man-db
procps-ng
util-linux
e2fsprogs
sysklogd
sysvinit
"

IFS=$'\n'; for s in $section;do
  # echo s7_$s
  frame m2_chroot package_scope $s s8_$s
done

#strip debug info (if desired)
#cleanup
# s8.78_cleanup

