#!/bin/bash
# Make the top of the m2 tree the root of the file system, then run the script

script="$1"
if [[ -z "$script" ]];then
  echo $0 requires a first argument as a script name
  exit
fi

# use a unique name just in case there are multiple install scripts running and someone
# has given the same name to two different scripts from different directories
script_name=$(basename $(mktemp -p $LFS/tmp -t))
script_path_m1="$LFS/tmp/$script_name"

# this is the path to the script in the m2 tree, relative to the top of the m2 tree
script_path_m2="/tmp/$script_name"

# Make a copy of the script in the m2 directory tree, because after the
# chroot command we will not be able to see the m1 directory tree anymore.
sudo cp "$script" "$script_path_m1"

if sudo chroot "$LFS" /usr/bin/env -i   \
    HOME=/root                  \
    TERM="$TERM"                \
    PS1='(lfs chroot) \u:\w\$ ' \
    PATH=/usr/bin:/usr/sbin     \
    SOURCE_DIR="$SOURCE_DIR"    \
    "$script_path_m2" ; then
  sudo cd $LFS
  sudo rm -rf source/$SOURCE_DIR
  sudo rm "$script_path_m1"
fi

