#!/bin/bash
script=$@

if [[ -z "$FRAME_LOG" ]];then
  export FRAME_LOG="frame.log"
fi
if [[ -z "$BUILD_LOG" ]];then
  export BUILD_LOG="build.log"
fi
    



cat >> "$BUILD_LOG" <<EOF

#--------------------------------------------------------------------------------
# start of:" $script
#
#
EOF

echo "#--------------------------------------------------------------------------------" >> "$FRAME_LOG"
Z >> "$FRAME_LOG"

echo $script >> "$FRAME_LOG"
{ /usr/bin/time -a -o "$FRAME_LOG" $script 2>&1 >&3 3>&- | tee -a "$FRAME_LOG" 3>&-; } >> "$BUILD_LOG" 3>&1

Z >> "$FRAME_LOG"
cat >> "$BUILD_LOG" <<EOF

#
#
# end of:" $script
#--------------------------------------------------------------------------------

EOF

