#!/bin/bash
script=$@

cat >> build.log <<EOF

#--------------------------------------------------------------------------------
# start of:" $script
#
#
EOF

echo "#--------------------------------------------------------------------------------" >> frame.log
Z >> frame.log
echo $script >> frame.log
#/usr/bin/time -a -o frame.log $script 2>> frame.log >> build.log
{ /usr/bin/time -a -o frame.log $script 2>&1 >&3 3>&- | tee -a frame.log 3>&-; } >> build.log 3>&1

Z >> frame.log
sleep .01

cat >> build.log <<EOF
#
#
# end of:" $script
#--------------------------------------------------------------------------------

EOF

