#!/bin/bash
# adds timing information and logging
#
script=$@

if [[ -z "$FRAME_LOG" ]];then
  export FRAME_LOG="frame.log"
fi
if [[ -z "$BUILD_LOG" ]];then
  export BUILD_LOG="build.log"
fi
    
stamp=$(Z)
cat <<EOF | tee -a "$FRAME_LOG" >> "$BUILD_LOG"

#--------------------------------------------------------------------------------
# $stamp
# start of: $script
#
#
EOF

#m2 does not have 'time'
# { /usr/bin/time -a -o "$FRAME_LOG" $script 2>&1 >&3 3>&- | tee -a "$FRAME_LOG" 3>&-; } >> "$BUILD_LOG" 3>&1
{ $script 2>&1 >&3 3>&- | tee -a "$FRAME_LOG" ; } >> "$BUILD_LOG" 3>&1

stamp=$(Z)
cat <<EOF | tee -a "$FRAME_LOG" >> "$BUILD_LOG"

#
#
# end of: $script
# $stamp
#--------------------------------------------------------------------------------

EOF

