#!/bin/bash
# this should be sourced from the calling script, not executed directly
# this returns the variables: package, SOURCE_DIR

package="$1"
if [ -z "$package" ]; then
  echo $0 requires a first parameter for the package name
  exit
fi

cd $M2_ROOT
if [[ ! -d source ]]; then
    mkdir source
fi
cd source

tar -xf "$M2_ROOT"/package/"$package"-*.tar*
export SOURCE_DIR=$(ls -d "$package"-*)
cd "$SOURCE_DIR"
