#!/bin/bash

./configure --prefix=/usr                   \
            --build=$(support/config.guess) \
            --host=$LFS_TGT                 \
            --without-bash-malloc
make
make DESTDIR=$M2_ROOT install
ln -sv bash $M2_ROOT/bin/sh


