#!/bin/bash
#
frame book_m1

# s7_14_checkpoint is suggested after chapter 7, but I prefer to checkpoint before the permissions changes
frame checkpoint m2_root_after_book_m1

# exports a copy of the scripts to m2_root and runs the pre-chroot portion of chapter 7
frame environment_root book_m1_to_m2

# This will be the last command that shows in the logs of the m1 build directory. After this the scripts start
# writing the logs in the m2_root/sbin/LFS directory.
frame environment_root environment_book_m2 book_m2
