#!/bin/bash

set -e

section="
binutils 
gcc
linux
glibc
"

IFS=$'\n'; for s in $section;do
  # echo s6_$s
  eval frame package_scope $s s5_$s
done

# libstdc++ is found in the gcc package:
frame package_scope gcc s5_libstdc++

