#!/bin/bash
# bash without -i resets PS1
# except for the log file variables this comes from section 4.4

script="$@"
if [[ -z "$script" ]]; then
  script="/bin/bash --norc"
fi

M2_ROOT="/mnt/m2_root"
LFS_BUILD_DIR="$REPO_HOME/LFS/LFS11"
env -i "$LFS_BUILD_DIR/executable/environment_book_m1-1"\
  "$PPS1"\
  "$PPS2"\
  "$REPO_HOME"\
  "$PROJECT_HOME"\
  "$PROJECT"\
  "$LFS_BUILD_DIR"\
  "$M2_ROOT"\
  "$FRAME_LOG"\
  "$BUILD_LOG"\
  $script
