#!/bin/bash
# bash without -i resets PS1
# Make the top of the m2 tree the root of the file system, then run the script
#set -x

script="$@"
if [[ -z "$script" ]]; then
  script="/bin/bash --norc"
fi

if [[ -z "$M2_ROOT" ]];then
  echo $0 "requires variable M2_ROOT to be set"
  exit
fi

if [[ -z "$TERM" ]];then
  echo $0 "requires variable TERM to be set"
  exit
fi

LFS_BUILD_DIR='$M2_ROOT/LFS11' # LFS 11 has been mounted here, see book_m1_to_m2
chroot "$M2_ROOT" /usr/bin/env -i "$LFS_BUILD_DIR/executable/environment_book_m2-1"\
  "$TERM"\
  "$PPS1"\
  "$PPS2"\
  "$PROJECT"\
  "$LFS_BUILD_DIR"\
  "$FRAME_LOG"\
  "$BUILD_LOG"\
  $script

#set +x
