#!/bin/bash
# bash without -i resets PS1
# Make the top of the m2 tree the root of the file system, then run the script
#set -x

term="$1"
pps1="$2"
pps2="$3"
project="$4"
lfs_build_dir="$5"
frame_log="$6"
build_log="$7"
script="${@:8}"

# stuff from the m1 environment we would like to keep
umask 022
M2_ROOT="/" # due to changeroot
LC_ALL=POSIX
MAKEFLAGS="-j12"  # this might cause problems for some builds
export M2_ROOT LC_ALL MAKEFLAGS

# according to the book for m2
HOME=/root		    
TERM="$term"		    
# set PS below ...  PS1="(lfs chroot) u:w$ " 
PATH=/usr/bin:/usr/sbin
export HOME TERM PATH

# repo environment
PROJECT="$project-book-m2"
export PROJECT

# for our build scripts
LFS_BUILD_DIR="$lfs_build_dir"
LFS_LOG_DIR="$LFS_BUILD_DIR/log"
LFS_ARCHIVE_DIR="$LFS_BUILD_DIR/archive"
PATH="$LFS_BUILD_DIR/executable/$PATH"
LFS_LOG_DIR="$LFS_BUILD_DIR/log"
FRAME_LOG="$frame_log"
BUILD_LOG="$build_log"
export LFS_BUILD_DIR LFS_LOG_DIR LFS_ARCHIVE_DIR PATH FRAME_LOG BUILD_LOG  

# prompt so that dirtrack works in emacs, timezone
PPS1="$PPS1"
PPS2="$PPS2"
PS1="$PPS1"
PS2="$PPS2"
TZ=UTC
TIME_STYLE=long-iso
export PPS1 PPS2 PS1 PS2 TZ TIME_STYLE

cd "$LFS_BUILD_DIR"

$script

#set +x
