#!/bin/bash
#   This script uses sudo -E to prevent the environment from being erased. Sudo only appears here
#   at the top level.
#
#   Be sure to modify the /etc/suders file so sudo does not ask for a password, otherwise a person will have to
#   be present to type the sudo password before it times out. Emacs tramp also gets messed up by the
#   sudo password prompts.
#   https://www.cyberciti.biz/faq/linux-unix-running-sudo-command-without-a-password/
#   https://thomas-cokelaer.info/blog/2011/05/fedora-how-to-add-a-sudo-user-and-avoid-password/
#   lfs 	ALL=(ALL) NOPASSWD:ALL
#
#  strange, on m1 I had to edit /etc/hosts or sudo would take a long time and (not work?)
#  https://www.linuxquestions.org/questions/linux-newbie-8/fedora-11-sudo-has-a-20-second-start-delay-732291/#post3575840
#
#  bash resets PS1 unless called with a -i option, so setting driectly here in case someone calls bash itself as $1
#

sudo -E \
  env \
    "PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"\
    "PROJECT=$PROJECT-root"\
    "PS1=\n$(/usr/local/bin/Z)[\$PROJECT]\n\u@\h§$PWD§\n> "\
    "PS2=>> "\
  $@
