#!/bin/bash

if [[ -z "$PROJECT_HOME" ]]; then
  echo "$0 requires variable PROJECT_HOME to be set"
  exit 1
fi

if [[ -z "$M2_ROOT" ]]; then
  echo "$0 requires variable M2_ROOT to be set"
  exit 1
fi

rm -f $M2_ROOT/usr/sbin/LFS/*
mkdir -p $M2_ROOT/usr/sbin/LFS
cp $PROJECT_HOME/executable/LFS/* $M2_ROOT/usr/sbin/LFS
cp /usr/local/bin/Z $M2_ROOT/usr/sbin/LFS
