#!/bin/bash
# adds timing information and logging
#
script=$@

if [[ -z "$FRAME_LOG" ]];then
  export FRAME_LOG="frame.log"
fi
if [[ -z "$BUILD_LOG" ]];then
  export BUILD_LOG="build.log"
fi

frame_log_path="$LFS_LOG_DIR/$FRAME_LOG"
build_lob_path="$LFS_LOG_DIR/$BUILD_LOG"

    
stamp=$(Z)
cat <<EOF | tee -a "$frame_log_path" >> "$build_log_path"

#--------------------------------------------------------------------------------
# $stamp
# start of: $script
#
#
EOF

#m2 does not have 'time'
# { /usr/bin/time -a -o "$frame_log_path" $script 2>&1 >&3 3>&- | tee -a "$frame_log_path" 3>&-; } >> "$build_log_path" 3>&1
#{ $script 2>&1 >&3 3>&- | tee -a "$frame_log_path" ; } >> "$build_log_path" 3>&1

{ { time $script ; } 2>&1 1>&3 | tee -a "$frame_log_path" ; } 1>> "$build_log_path" 3>&1

stamp=$(Z)
cat <<EOF | tee -a "$frame_log_path" >> "$build_log_path"

#
#
# end of: $script
# $stamp
#--------------------------------------------------------------------------------

EOF

