#!/bin/bash

if [[ -z "$FRAME_LOG" ]];then
  export FRAME_LOG="frame.log"
fi
if [[ -z "$BUILD_LOG" ]];then
  export BUILD_LOG="build.log"
fi

stamp=$(Z)
cat <<EOF | tee "$FRAME_LOG" | tee "$BUILD_LOG"
#--------------------------------------------------------------------------------
# $stamp
# resetting frame log: "$FRAME_LOG"
# resetting build log: "$BUILD_LOG"
#--------------------------------------------------------------------------------
EOF
