#!/bin/bash
# This might require sudo_LFS depending on the stage in the build that it is run at.
# This is dangerous. This is the kind of thing that causes a person to use an emulated m1 machine.
set -x
set -e

if [[ -z "$M2_ROOT" ]];then
  echo $0 " requires that \$M2_ROOT has a value"
  exit 1
fi

# run m2_wipe as root so that umount will work and rm of files works even when the files are owned by root
# this is an excellent script for wiping your host computer by accident!
if [ "$EUID" -ne 0 ]; then
  echo $0 "not being run as root, so can't do unounts, we stop scanning upon reaching the first error"
fi

read -p "Remove all files except package/ on $M2_ROOT? [y|n]:" -n 1 -r
echo    # (optional) move to a new line
if [[ ! "$REPLY" =~ ^[y]$ ]];then
  exit 1
fi

# found that the absolute pathname is necessary, independent of the current pwd
umount /mnt/m2_root/LFS11 || true
rmdir LFS11 || true

umount /mnt/m2_root/run || true
umount /mnt/m2_root/sys || true
umount /mnt/m2_root/proc || true
umount /mnt/m2_root/dev/pts devpts || true
umount /mnt/m2_root/dev/pts  || true
umount /mnt/m2_root/dev || true

echo "rm -rf the following:"
find "$M2_ROOT" \
  -maxdepth 1 -mindepth 1 \
  ! -name "LFS11" \
  -print \
  \( -exec rm -rf {} \; -o -quit \)

chown "$USERNAME":"$USERNAME" "$M2_ROOT"
chmod 0755 "$M2_ROOT"

set +x
