#!/bin/bash

if [[ -z "$M2_ROOT" ]]; then
  echo "$0: M2_ROOT must have a value"
  exit 1
fi

if [[ ! -d "$M2_ROOT/LFS11" ]]; then
  mkdir "$M2_ROOT/LFS11"
fi

mount --bind "$LFS_BUILD_DIR" "$M2_ROOT/LFS11"
