#!/bin/bash

tar -xf "$LFS_BUILD_DIR"/package/mpfr-*.tar.*
tar -xf "$LFS_BUILD_DIR"/package/gmp-*.tar.*
tar -xf "$LFS_BUILD_DIR"/package/mpc-*.tar.*

mv -v mpfr-* mpfr
mv -v gmp-* gmp
mv -v mpc-* mpc

case $(uname -m) in
  x86_64)
    sed -e '/m64=/s/lib64/lib/' -i.orig gcc/config/i386/t-linux64
  ;;
esac

mkdir -v build
cd       build

mkdir -pv $LFS_TGT/libgcc
ln -s ../../../libgcc/gthr-posix.h $LFS_TGT/libgcc/gthr-default.h

../configure                                       \
    --build=$(../config.guess)                     \
    --host=$LFS_TGT                                \
    --prefix=/usr                                  \
    CC_FOR_TARGET=$LFS_TGT-gcc                     \
    --with-build-sysroot=$M2_ROOT                      \
    --enable-initfini-array                        \
    --disable-nls                                  \
    --disable-multilib                             \
    --disable-decimal-float                        \
    --disable-libatomic                            \
    --disable-libgomp                              \
    --disable-libquadmath                          \
    --disable-libssp                               \
    --disable-libvtv                               \
    --disable-libstdcxx                            \
    --enable-languages=c,c++

make
make DESTDIR=$M2_ROOT install
ln -sv gcc $M2_ROOT/usr/bin/cc

