#!/bin/bash

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/expat-2.4.6

make
make check
make install
# documentation
install -v -m644 doc/*.{html,css} /usr/share/doc/expat-2.4.6