#!/bin/bash

./configure --prefix=/usr                      \
            --docdir=/usr/share/doc/"$PACKAGE" \
            --disable-static                   \
            --disable-kill

make
make check
make install
